<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <!-- Prevents Build/debug/net9.0 -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>Build\$(Configuration)\</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DreambitEngine\MonoGame\MonoGame.Framework\MonoGame.Framework.Native.csproj" />
    <ProjectReference Include="..\DreambitEngine\DreambitEngine\DreambitEngine.csproj" />
    <ProjectReference Include="..\DreambitEngine\Dreambit.Content\Dreambit.Content.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\TDGame.Content\TDGame.Content.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
