<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>

    <!-- Prevents Build/debug/net9.0 -->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <OutputPath>Build\$(Configuration)\</OutputPath>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    
    <MonoGamePlatform>DesktopVK</MonoGamePlatform>
    <IsTDGameHost>true</IsTDGameHost>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico">
      <LogicalName>Icon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Icon.bmp">
      <LogicalName>Icon.bmp</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DreambitEngine\MonoGame\MonoGame.Framework\MonoGame.Framework.Native.csproj" />
    <ProjectReference Include="..\DreambitEngine\MonoGame\src\NuGetPackages\MonoGame.Runtime.Windows.Vulkan\MonoGame.Runtime.Windows.Vulkan.csproj" />
    <ProjectReference Include="..\DreambitEngine\MonoGame\src\NuGetPackages\MonoGame.Runtime.Mac.Vulkan\MonoGame.Runtime.Mac.Vulkan.csproj" />
    <ProjectReference Include="..\DreambitEngine\MonoGame\src\NuGetPackages\MonoGame.Runtime.Linux.Vulkan\MonoGame.Runtime.Linux.Vulkan.csproj" />
    <ProjectReference Include="..\DreambitEngine\Dreambit.Content\Dreambit.Content.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\TDGame.Content\TDGame.Content.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\TDGame.Core\TDGame.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Include="..\DreambitEngine\Dreambit.Content\Assets\**\*" />
    <UpToDateCheckInput Include="..\TDGame.Content\Assets\**\*" />
  </ItemGroup>

  <Import Project="..\TDGame.Content\BuildContent.targets" />
  <Import Project="..\DreambitEngine\Dreambit.Content\BuildContent.targets" />
</Project>
