<Project>
  <PropertyGroup>
    <TDGameContentBuilderProject>$(MSBuildThisFileDirectory)TDGame.Content.csproj</TDGameContentBuilderProject>
    <TDGameContentBuilderDll>$(MSBuildThisFileDirectory)bin\$(Configuration)\TDGame.Content.dll</TDGameContentBuilderDll>
    <TDGameContentSource>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)\Assets'))</TDGameContentSource>
    <TDGameContentOutput>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\Build\$(Configuration)'))</TDGameContentOutput>
    <TDGameContentIntermediate>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\obj\$(Configuration)\TDGameContent'))</TDGameContentIntermediate>
    <TDGameAssetBakerProject>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)\..\DreambitEngine\DreambitEngine.AssetBaker\DreambitEngine.AssetBaker.csproj'))</TDGameAssetBakerProject>
    <TDGameAssetBakerDll>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)\..\DreambitEngine\DreambitEngine.AssetBaker\Build\$(Configuration)\AssetBaker.dll'))</TDGameAssetBakerDll>
    <TDGamePakOutput>$(TDGameContentOutput)\Content\content.pak</TDGamePakOutput>
  </PropertyGroup>

  <ItemGroup>
    <TDGamePakInput Include="$(TDGameContentSource)\**\*.png;$(TDGameContentSource)\**\*.jpg;$(TDGameContentSource)\**\*.jpeg;$(TDGameContentSource)\**\*.bmp;$(TDGameContentSource)\**\*.tga;$(TDGameContentSource)\**\*.json;$(TDGameContentSource)\**\*.ldtk;$(TDGameContentSource)\**\*.ldtkl;$(TDGameContentSource)\**\*.yaml;$(TDGameContentSource)\**\*.yml;$(TDGameContentSource)\**\*.wav;$(TDGameContentSource)\**\*.ogg;$(TDGameContentSource)\**\*.mp3" />
  </ItemGroup>

  <Target
    Name="BakeTDGamePak"
    Inputs="@(TDGamePakInput)"
    Outputs="$(TDGamePakOutput)">
    <MSBuild
      Projects="$(TDGameAssetBakerProject)"
      Targets="Build"
      Properties="Configuration=$(Configuration)"
      RemoveProperties="TargetFramework;RuntimeIdentifier;RuntimeIdentifiers;OutputPath;BaseOutputPath" />

    <Exec Command="dotnet &quot;$(TDGameAssetBakerDll)&quot; bake-pak &quot;$(TDGameContentSource)&quot; &quot;$(TDGamePakOutput)&quot;" />
  </Target>

  <Target
    Name="BuildTDGameContent"
    BeforeTargets="BeforeCompile"
    DependsOnTargets="BakeTDGamePak">

    <MSBuild
            Projects="$(TDGameContentBuilderProject)"
            Targets="Build"
            Properties="Configuration=$(Configuration)"
            RemoveProperties="TargetFramework;RuntimeIdentifier;RuntimeIdentifiers;OutputPath;BaseOutputPath" />

    <Exec
            Command="dotnet &quot;$(TDGameContentBuilderDll)&quot; build -p &quot;$(MonoGamePlatform)&quot; -s &quot;$(TDGameContentSource)&quot; -o &quot;$(TDGameContentOutput)&quot; -i &quot;$(TDGameContentIntermediate)&quot;"
            CustomErrorRegularExpression="\[E\] .+"
            CustomWarningRegularExpression="\[W\] .+" />
  </Target>
</Project>
